dist: xenial
language: python
python:
  - "3.5"

install:
  - pip install poetry
  - poetry config settings.virtualenvs.create false
  - poetry install --no-interaction

script:
  - poetry run pylint --exit-zero edustream
  - poetry run pytest
